vpc_cidr_block    = "10.0.0.0/16"
subnet_cidr_block = "10.0.10.0/24"
avail_zone        = "ap-southeast-2b"
env_prefix        = "dev"
my_ip             = "0.0.0.0/0"
instance_type = "t2.micro"
public_key_location = "/Users/arnaldo/.ssh/id_rsa.pub"
private_key_location = "/Users/arnaldo/.ssh/id_rsa"